# Generated by Django 3.0.2 on 2020-01-24 03:02

import django.contrib.postgres.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='card1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='card2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='card3',
        ),
        migrations.AddField(
            model_name='profile',
            name='savedCards',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=200), default=[], size=None),
            preserve_default=False,
        ),
    ]
