# Generated by Django 3.0.2 on 2020-01-24 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200123_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='savedCards',
        ),
    ]
