# Generated by Django 3.0.2 on 2020-01-24 04:01

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_profile_savedcards'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='savedCards',
            field=django.contrib.postgres.fields.jsonb.JSONField(default='{cards:[]}'),
        ),
    ]
